---
version: '3.6'
services:
    portainer:
        image: portainer/portainer:latest
        environment:
          HTTP_EXPOSE: 80:80,8025:8025,9001:9000
          HTTPS_EXPOSE: 443:80,8026:8025,8001:9000
        restart:  always
        container_name: ddev-${DDEV_SITENAME}-portainer
        labels:
          com.ddev.site-name: ${DDEV_SITENAME}
          com.ddev.approot: $DDEV_APPROOT
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data
        external_links:
            - "ddev-router:${DDEV_HOSTNAME}"
        cap_add:
            - SYS_ADMIN
        expose:
          - '9000'
volumes:
  portainer_data:

networks:
  default:
    external:
      name: ddev_default

